In [5]:
import numpy as np
a = np.array([1, 2, 3]) #Create a rank 1 Array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 100 # Change an element of the array
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[100   2   3]


In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]]) #rank 2 array
print(b.shape)
print(b[0, 0], b[1,1])


(2, 3)
1 5


In [11]:
a = np.zeros((2, 2)) # Create an array of all zeros
print(a) # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"
    
b = np.ones((1, 2)) # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


c = np.full((2, 2), 7) # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"
    
    

d = np.eye(2)
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
