In [8]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]

print(a)
print("--------------")

print(b)
print("--------------")
print(a[0, 1])
print("--------------")
b[0, 0] = 77
print(b)
print("--------------")
print(a[0, 1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------
[[2 3]
 [6 7]]
--------------
2
--------------
[[77  3]
 [ 6  7]]
--------------
77


In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) #rank 2
row_r1 = a[1, :]
print(row_r1, row_r1.shape) #[5 6 7 8] (4,)

row_r2 = a[1:2, :]
print(row_r2, row_r2.shape) #[[5 6 7 8]] (1, 4)

col_c = a[:, 1]
print(col_c , col_c .shape) #[ 2  6 10] (3,)

col_c2 = a[:, 1:2]
print(col_c2, col_c2.shape) #[ 2  6 10] (3,)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
