In [4]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

                 # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"
                        
                        
                        
print(a[bool_idx]) #[3 4 5 6]
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [10]:
###Math###

x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5, 6], [7,8]], dtype=np.float64)

print(x + y) 
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))


print(x / y)
print(np.divide(x, y))


print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [15]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))

print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
